# This file was generated by GoReleaser. DO NOT EDIT.
cask "systemd-tui" do
  version "0.1.0-rc6"

  on_macos do
    on_intel do
      sha256 "fd008aded8e318e91b6d731011197f63cb07c4f0c5cf6e351e5eef0dd8e50e26"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "87baa85e80f94b60d890dbadb0d324d1ab37a3abf7bba1dc7a396b437bd8ee6d"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88903bb61dd16cba05374dd676e8c6425e68d95ec46b65b1e7700f0486ce9be9"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d23a9835f289a4209145b1b15b176d5ceac24e4508d867bedebd98fc5f3183e1"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "systemd-tui"
  desc "Interactive TUI for systemd over D-Bus"
  homepage "https://github.com/ptrvsrg/systemd-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "systemd-tui"

  # No zap stanza required

end
