# This file was generated by GoReleaser. DO NOT EDIT.
cask "systemd-tui" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6a373c4abbd5f842b5eb2c2f6ed7f70219d3a1c6e487d6f9f5e0f0a5b40a4ed3"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97653971fe94f6ab0c81a8eed3a4181a88d44f51d9e7b0bcda24cbab903aa381"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3006c9edcb9c729d55d915b1db8bcb6401b496a48c34f981edb9ae3141520d05"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b86d005846e9569353808982559147e3fd5c66407cf654bd5a8d7f4ee2ab83b9"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "systemd-tui"
  desc "Interactive TUI for systemd over D-Bus"
  homepage "https://github.com/ptrvsrg/systemd-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "systemd-tui"

  # No zap stanza required

end
