# This file was generated by GoReleaser. DO NOT EDIT.
cask "systemd-tui" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "75266fb0c3190e2c23e48af66e9400eea3b59a17506dea611a68f5ef60031737"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8576031af59cffb1007902e3cfaa357676196e157ec3913586ab051455820458"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6713b4b1fbfe17892b66b38963b1940a5a7f61c373b16026ef0e1c1aeb43272b"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f169bc9e2fa81090b364fae191104e410f7928bf9faf9ec907771fdaa7423da5"
      url "https://github.com/ptrvsrg/systemd-tui/releases/download/v#{version}/systemd-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "systemd-tui"
  desc "Interactive TUI for systemd over D-Bus"
  homepage "https://github.com/ptrvsrg/systemd-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "systemd-tui"

  # No zap stanza required

end
